[project]
name = "slidesage"
revision = "1.0"

[profiles.default]
AUTH_SECRET = { description = "AUTH_SECRET secret", required = true }
BASE_URL = { description = "BASE_URL secret", required = true }
BETTER_AUTH_TRUSTED_ORIGINS = { description = "BETTER_AUTH_TRUSTED_ORIGINS secret", required = true }
CLOUDFLARE_API_TOKEN = { description = "CLOUDFLARE_API_TOKEN secret", required = true }
CORS_ORIGINS = { description = "CORS_ORIGINS secret", required = true }
DATABASE_CONNECT_TIMEOUT = { description = "DATABASE_CONNECT_TIMEOUT secret" }
DATABASE_URL = { description = "DATABASE_URL secret", required = true }
EMBEDDING_MODEL = { description = "EMBEDDING_MODEL secret", required = true }
EXA_API_KEY = { description = "EXA_API_KEY secret", required = true }
GITHUB_CLIENT_ID = { description = "GITHUB_CLIENT_ID secret", required = true }
GITHUB_CLIENT_SECRET = { description = "GITHUB_CLIENT_SECRET secret", required = true }
GOOGLE_CLIENT_ID = { description = "GOOGLE_CLIENT_ID secret", required = true }
GOOGLE_CLIENT_SECRET = { description = "GOOGLE_CLIENT_SECRET secret", required = true }
HOST = { description = "HOST secret", required = true }
NODE_ENV = { description = "NODE_ENV secret" }
OPEN_ROUTER_API_BASE = { description = "OPEN_ROUTER_API_BASE secret", required = true }
OPEN_ROUTER_API_KEY = { description = "OPEN_ROUTER_API_KEY secret", required = true }
OPEN_ROUTER_EMBEDDINGS_URL = { description = "OPEN_ROUTER_EMBEDDINGS_URL secret", required = true }
OPEN_ROUTER_MODEL = { description = "OPEN_ROUTER_MODEL secret", required = true }
POLICY_AUD = { description = "POLICY_AUD secret", required = true }
PORT = { description = "PORT secret", required = true }
RAZORPAY_KEY_ID = { description = "RAZORPAY_KEY_ID secret", required = true }
RAZORPAY_KEY_SECRET = { description = "RAZORPAY_KEY_SECRET secret", required = true }
RESEND_API_KEY = { description = "RESEND_API_KEY secret", required = true }
RESEND_FROM_EMAIL = { description = "RESEND_FROM_EMAIL secret", required = true }
TEAM_DOMAIN = { description = "TEAM_DOMAIN secret", required = true }
VITE_API_URL = { description = "VITE_API_URL secret", required = true }
VITE_PROXY_TARGET = { description = "VITE_PROXY_TARGET secret", required = true }

