#!/usr/bin/env bash
# Regenerate cloudflare.conf from Cloudflare's published edge ranges. Run it
# when Cloudflare announces a change, then reload nginx:
#   docker compose exec nginx nginx -s reload
set -euo pipefail

target="$(dirname "$0")/nginx/cloudflare.conf"
# Fetch separately so a failed IPv4 request cannot be masked by IPv6 success.
ipv4=$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v4)
ipv6=$(curl -fsS --max-time 10 https://www.cloudflare.com/ips-v6)
if [[ -z $ipv4 || -z $ipv6 ]] \
	|| grep -qEv '^[0-9.]+/[0-9]+$' <<<"$ipv4" \
	|| grep -qEv '^[0-9a-f:]+/[0-9]+$' <<<"$ipv6"; then
	echo "invalid ranges fetched; leaving $target unchanged" >&2
	exit 1
fi
ranges=$(printf '%s\n%s\n' "$ipv4" "$ipv6")

{
	echo "# Generated by refresh-cloudflare-ips.sh. Do not edit by hand."
	echo
	echo "# Replace \$remote_addr with the visitor address Cloudflare reports."
	echo "real_ip_header CF-Connecting-IP;"
	while read -r range; do
		echo "set_real_ip_from $range;"
	done <<<"$ranges"
	echo
	echo "# realip rewrites \$remote_addr before the access phase, so check the"
	echo "# address that actually connected."
	echo "geo \$realip_remote_addr \$from_cloudflare {"
	printf '\tdefault 0;\n'
	while read -r range; do
		printf '\t%s 1;\n' "$range"
	done <<<"$ranges"
	echo "}"
} >"$target.tmp"
# Overwrite in place rather than renaming: nginx sees this file through a
# single-file bind mount, which keeps pointing at the original inode.
cat "$target.tmp" >"$target"
rm "$target.tmp"
echo "wrote $(wc -l <<<"$ranges") ranges to $target"
