export interface TemplateStyles {
	slideContent: React.CSSProperties;
	slideTitle: React.CSSProperties;
	slideSubtitle: React.CSSProperties;
	slideList: React.CSSProperties;
	slideTable: React.CSSProperties;
	slideTableTh: React.CSSProperties;
	slideTableTd: React.CSSProperties;
	slideQuote: React.CSSProperties;
	slideDescription: React.CSSProperties;
	slideHighlight: React.CSSProperties;
	slideStats: React.CSSProperties;
	slideKeypoint: React.CSSProperties;
	slideImage: React.CSSProperties;
	twoColumn: React.CSSProperties;
	column: React.CSSProperties;
}

export interface Template {
	id: string;
	name: string;
	description: string;
	styles: TemplateStyles;
	backgroundClass?: string;
}

export const AVAILABLE_TEMPLATES: Template[] = [
	{
		id: "modern-dark",
		name: "Modern Dark",
		description: "Sleek dark theme with neon accents",
		backgroundClass: "bg-slate-900",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "3rem",
				background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
				color: "#f8fafc",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Inter', sans-serif",
			},
			slideTitle: {
				fontSize: "3rem",
				fontWeight: 800,
				background: "linear-gradient(to right, #38bdf8, #818cf8)",
				WebkitBackgroundClip: "text",
				WebkitTextFillColor: "transparent",
				marginBottom: "1.5rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
				letterSpacing: "-0.02em",
			},
			slideSubtitle: {
				fontSize: "1.5rem",
				fontWeight: 500,
				color: "#94a3b8",
				marginBottom: "2.5rem",
				textAlign: "center",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 1.8,
				margin: "3rem 0",
				padding: "2rem",
				background: "rgba(30, 41, 59, 0.5)",
				borderRadius: "16px",
				border: "1px solid rgba(148, 163, 184, 0.1)",
				listStyleType: "disc",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "separate",
				borderSpacing: "0",
				margin: "2rem 0",
				background: "rgba(30, 41, 59, 0.5)",
				borderRadius: "16px",
				overflow: "hidden",
				border: "1px solid rgba(148, 163, 184, 0.1)",
			},
			slideTableTh: {
				background: "rgba(56, 189, 248, 0.1)",
				color: "#38bdf8",
				padding: "1.25rem",
				textAlign: "left",
				fontWeight: 600,
				borderBottom: "1px solid rgba(148, 163, 184, 0.1)",
			},
			slideTableTd: {
				padding: "1rem 1.25rem",
				borderBottom: "1px solid rgba(148, 163, 184, 0.1)",
				color: "#cbd5e1",
			},
			slideQuote: {
				fontSize: "2rem",
				fontStyle: "italic",
				color: "#f8fafc",
				margin: "3rem 0",
				padding: "2rem",
				borderLeft: "4px solid #38bdf8",
				background:
					"linear-gradient(90deg, rgba(56, 189, 248, 0.1) 0%, transparent 100%)",
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#94a3b8",
				fontSize: "1.1rem",
				textAlign: "center",
				marginTop: "1rem",
			},
			slideHighlight: {
				background: "linear-gradient(135deg, #38bdf8, #818cf8)",
				color: "white",
				padding: "2rem",
				borderRadius: "16px",
				margin: "2rem 0",
				textAlign: "center",
				boxShadow: "0 10px 25px -5px rgba(56, 189, 248, 0.3)",
			},
			slideStats: {
				display: "grid",
				gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
				gap: "2rem",
				margin: "2rem 0",
				width: "100%",
			},
			slideKeypoint: {
				background: "rgba(30, 41, 59, 0.5)",
				padding: "1.5rem",
				borderRadius: "12px",
				textAlign: "center",
				border: "1px solid rgba(148, 163, 184, 0.1)",
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				borderRadius: "16px",
				margin: "2rem auto",
				display: "block",
				boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.3)",
			},
			twoColumn: {
				display: "flex",
				gap: "3rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
				borderTop: "1px solid rgba(148, 163, 184, 0.2)",
				paddingTop: "2rem",
				backgroundImage:
					"linear-gradient(rgba(148, 163, 184, 0.2), rgba(148, 163, 184, 0.2))",
				backgroundSize: "1px 100%",
				backgroundPosition: "center",
				backgroundRepeat: "no-repeat",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "1rem",
			},
		},
	},
	{
		id: "corporate-blue",
		name: "Corporate Blue",
		description: "Professional",
		backgroundClass: "bg-white",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "4rem",
				background: "#ffffff",
				color: "#0f172a",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Inter', sans-serif",
			},
			slideTitle: {
				fontSize: "3rem",
				fontWeight: 800,
				color: "#1e40af",
				marginBottom: "1rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
				position: "relative",
			},
			slideSubtitle: {
				fontSize: "1.5rem",
				fontWeight: 600,
				color: "#334155",
				marginBottom: "3rem",
				textAlign: "center",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 1.6,
				margin: "3rem 0",
				padding: "0",
				listStyleType: "disc",
				color: "#1e293b",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "collapse",
				margin: "2rem 0",
				boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
				border: "1px solid #e2e8f0",
			},
			slideTableTh: {
				background: "#1e40af",
				color: "white",
				padding: "1rem",
				textAlign: "left",
				fontWeight: 700,
				textTransform: "uppercase",
				fontSize: "0.875rem",
				letterSpacing: "0.05em",
			},
			slideTableTd: {
				padding: "1rem",
				borderBottom: "1px solid #e2e8f0",
				color: "#334155",
				fontWeight: 500,
			},
			slideQuote: {
				fontSize: "2.25rem",
				fontWeight: 600,
				color: "#1e40af",
				margin: "15rem 2rem",
				lineHeight: 2,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#475569",
				fontSize: "1.1rem",
				textAlign: "center",
				marginTop: "1rem",
				fontWeight: 500,
			},
			slideHighlight: {
				background: "#eff6ff",
				color: "#1e3a8a",
				padding: "2rem",
				borderRadius: "8px",
				margin: "2rem 0",
				textAlign: "center",
				borderLeft: "6px solid #2563eb",
				fontWeight: 600,
			},
			slideStats: {
				display: "flex",
				justifyContent: "space-around",
				gap: "2rem",
				margin: "3rem 0",
				width: "100%",
			},
			slideKeypoint: {
				textAlign: "center",
				padding: "1rem",
				color: "#1e3a8a",
				fontWeight: 600,
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				borderRadius: "8px",
				margin: "2rem auto",
				display: "block",
				boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
				border: "1px solid #e2e8f0",
			},
			twoColumn: {
				display: "flex",
				gap: "4rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
				borderTop: "2px solid #e2e8f0",
				paddingTop: "2rem",
				backgroundImage: "linear-gradient(#e2e8f0, #e2e8f0)",
				backgroundSize: "2px 100%",
				backgroundPosition: "center",
				backgroundRepeat: "no-repeat",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "1rem",
			},
		},
	},
	{
		id: "minimalist",
		name: "Minimalist",
		description: "Clean, airy, and sophisticated",
		backgroundClass: "bg-stone-50",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "4rem",
				background: "#fafaf9",
				color: "#1c1917",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Inter', sans-serif",
			},
			slideTitle: {
				fontSize: "3.5rem",
				fontWeight: 300,
				color: "#1c1917",
				marginBottom: "1.5rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
				letterSpacing: "-0.03em",
			},
			slideSubtitle: {
				fontSize: "1.25rem",
				fontWeight: 400,
				color: "#78716c",
				marginBottom: "4rem",
				textAlign: "center",
				textTransform: "uppercase",
				letterSpacing: "0.1em",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 2,
				margin: "3rem 0",
				paddingLeft: "0",
				listStyleType: "circle",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "collapse",
				margin: "3rem 0",
			},
			slideTableTh: {
				background: "transparent",
				color: "#1c1917",
				padding: "1rem 0",
				textAlign: "left",
				fontWeight: 500,
				borderBottom: "2px solid #1c1917",
			},
			slideTableTd: {
				padding: "1.5rem 0",
				borderBottom: "1px solid #e7e5e4",
				color: "#44403c",
			},
			slideQuote: {
				fontSize: "2.5rem",
				fontStyle: "italic",
				fontFamily: "serif",
				color: "#1c1917",
				margin: "4rem 0",
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#78716c",
				fontSize: "1rem",
				textAlign: "center",
				marginTop: "2rem",
				fontStyle: "italic",
			},
			slideHighlight: {
				background: "#e7e5e4",
				color: "#1c1917",
				padding: "3rem",
				margin: "3rem 0",
				textAlign: "center",
			},
			slideStats: {
				display: "flex",
				justifyContent: "space-between",
				gap: "4rem",
				margin: "4rem 0",
				width: "100%",
			},
			slideKeypoint: {
				textAlign: "center",
				padding: "1rem",
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				margin: "2rem auto",
				display: "block",
				filter: "grayscale(100%)",
			},
			twoColumn: {
				display: "flex",
				gap: "5rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
				borderTop: "1px solid #e7e5e4",
				paddingTop: "2rem",
				backgroundImage: "linear-gradient(#e7e5e4, #e7e5e4)",
				backgroundSize: "1px 100%",
				backgroundPosition: "center",
				backgroundRepeat: "no-repeat",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "2rem",
			},
		},
	},
	{
		id: "creative-studio",
		name: "Creative Studio",
		description: "Bold, vibrant, and artistic",
		backgroundClass: "bg-orange-500",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "3rem",
				background:
					"linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)",
				color: "#2d3748",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Poppins', sans-serif",
			},
			slideTitle: {
				fontSize: "3.5rem",
				fontWeight: 900,
				color: "#c026d3",
				marginBottom: "1rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
				textTransform: "uppercase",
				letterSpacing: "-0.05em",
				lineHeight: 1,
			},
			slideSubtitle: {
				fontSize: "1.5rem",
				fontWeight: 700,
				color: "#db2777",
				marginBottom: "2.5rem",
				textAlign: "center",
				letterSpacing: "0.05em",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 1.6,
				margin: "3rem 0",
				background: "rgba(255, 255, 255, 0.8)",
				padding: "2rem",
				borderRadius: "0",
				boxShadow: "10px 10px 0px rgba(0,0,0,0.1)",
				listStyleType: "square",
				border: "3px solid #2d3748",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "separate",
				borderSpacing: "0",
				margin: "2rem 0",
				background: "white",
				border: "3px solid #2d3748",
				boxShadow: "10px 10px 0px rgba(0,0,0,0.1)",
			},
			slideTableTh: {
				background: "#2d3748",
				color: "white",
				padding: "1.25rem",
				textAlign: "left",
				fontWeight: 700,
				textTransform: "uppercase",
			},
			slideTableTd: {
				padding: "1rem 1.25rem",
				borderBottom: "2px solid #2d3748",
				color: "#2d3748",
				fontWeight: 600,
			},
			slideQuote: {
				fontSize: "2.5rem",
				fontWeight: 800,
				color: "#2d3748",
				margin: "3rem 0",
				padding: "2rem",
				background: "#fef3c7",
				border: "3px solid #2d3748",
				boxShadow: "10px 10px 0px rgba(0,0,0,0.1)",
				transform: "rotate(-1deg)",
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#4a5568",
				fontSize: "1.2rem",
				textAlign: "center",
				marginTop: "1rem",
				fontWeight: 600,
			},
			slideHighlight: {
				background: "#c084fc",
				color: "white",
				padding: "2.5rem",
				margin: "2rem 0",
				textAlign: "center",
				border: "3px solid #2d3748",
				boxShadow: "10px 10px 0px #2d3748",
				fontWeight: 700,
			},
			slideStats: {
				display: "grid",
				gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
				gap: "2rem",
				margin: "2rem 0",
				width: "100%",
			},
			slideKeypoint: {
				background: "white",
				padding: "1.5rem",
				textAlign: "center",
				border: "3px solid #2d3748",
				boxShadow: "5px 5px 0px rgba(0,0,0,0.1)",
				fontWeight: 700,
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				border: "3px solid #2d3748",
				margin: "2rem auto",
				display: "block",
				boxShadow: "15px 15px 0px rgba(0,0,0,0.2)",
			},
			twoColumn: {
				display: "flex",
				gap: "3rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "1rem",
			},
		},
	},
	{
		id: "elegant-serif",
		name: "Elegant Serif",
		description: "Timeless, classic, and sophisticated",
		backgroundClass: "bg-stone-100",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "4rem",
				background: "#f5f5f4",
				color: "#44403c",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Playfair Display', serif",
			},
			slideTitle: {
				fontSize: "3.5rem",
				fontWeight: 400,
				color: "#292524",
				marginBottom: "1.5rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
				fontStyle: "italic",
			},
			slideSubtitle: {
				fontSize: "1.25rem",
				fontWeight: 400,
				color: "#a8a29e",
				marginBottom: "4rem",
				textAlign: "center",
				textTransform: "uppercase",
				letterSpacing: "0.2em",
				fontFamily: "'Inter', sans-serif",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 2,
				margin: "3rem 0",
				paddingLeft: "0",
				listStyleType: "disc",
				fontFamily: "'Inter', sans-serif",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "collapse",
				margin: "3rem 0",
				fontFamily: "'Inter', sans-serif",
			},
			slideTableTh: {
				background: "transparent",
				color: "#292524",
				padding: "1rem 0",
				textAlign: "left",
				fontWeight: 600,
				borderBottom: "1px solid #292524",
				textTransform: "uppercase",
				letterSpacing: "0.1em",
				fontSize: "0.875rem",
			},
			slideTableTd: {
				padding: "1.5rem 0",
				borderBottom: "1px solid #e7e5e4",
				color: "#57534e",
			},
			slideQuote: {
				fontSize: "2.5rem",
				fontStyle: "italic",
				color: "#292524",
				margin: "4rem 0",
				lineHeight: 1.4,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#78716c",
				fontSize: "1rem",
				textAlign: "center",
				marginTop: "2rem",
				fontFamily: "'Inter', sans-serif",
			},
			slideHighlight: {
				background: "#e7e5e4",
				color: "#292524",
				padding: "3rem",
				margin: "3rem 0",
				textAlign: "center",
				fontStyle: "italic",
			},
			slideStats: {
				display: "flex",
				justifyContent: "space-between",
				gap: "4rem",
				margin: "4rem 0",
				width: "100%",
				fontFamily: "'Inter', sans-serif",
			},
			slideKeypoint: {
				textAlign: "center",
				padding: "1rem",
				borderTop: "1px solid #d6d3d1",
				borderBottom: "1px solid #d6d3d1",
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				margin: "2rem auto",
				display: "block",
				filter: "sepia(20%)",
			},
			twoColumn: {
				display: "flex",
				gap: "5rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
				borderTop: "1px solid #d6d3d1",
				paddingTop: "2rem",
				backgroundImage: "linear-gradient(#d6d3d1, #d6d3d1)",
				backgroundSize: "1px 100%",
				backgroundPosition: "center",
				backgroundRepeat: "no-repeat",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "2rem",
			},
		},
	},
	{
		id: "nature-green",
		name: "Nature Green",
		description: "Fresh and organic",
		backgroundClass: "bg-green-50",
		styles: {
			slideContent: {
				width: "100%",
				height: "100%",
				padding: "3rem",
				background: "linear-gradient(180deg, #f0fdf4 0%, #dcfce7 100%)",
				color: "#14532d",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				boxSizing: "border-box",
				fontFamily: "'Inter', sans-serif",
			},
			slideTitle: {
				fontSize: "3rem",
				fontWeight: 700,
				color: "#15803d",
				marginBottom: "1rem",
				justifyContent: "center",
				display: "flex",
				alignItems: "center",
			},
			slideSubtitle: {
				fontSize: "1.5rem",
				fontWeight: 500,
				color: "#166534",
				marginBottom: "2.5rem",
				textAlign: "center",
			},
			slideList: {
				fontSize: "1.25rem",
				lineHeight: 1.8,
				margin: "3rem 0",
				background: "rgba(255, 255, 255, 0.6)",
				padding: "2rem",
				borderRadius: "20px",
				boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
				listStyleType: "disc",
			},
			slideTable: {
				width: "100%",
				borderCollapse: "separate",
				borderSpacing: "0",
				margin: "2rem 0",
				background: "rgba(255, 255, 255, 0.6)",
				borderRadius: "20px",
				overflow: "hidden",
				boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
			},
			slideTableTh: {
				background: "#22c55e",
				color: "white",
				padding: "1.25rem",
				textAlign: "left",
				fontWeight: 600,
			},
			slideTableTd: {
				padding: "1rem 1.25rem",
				borderBottom: "1px solid #dcfce7",
				color: "#14532d",
			},
			slideQuote: {
				fontSize: "2rem",
				fontStyle: "italic",
				color: "#15803d",
				margin: "3rem 0",
				padding: "2rem",
				background: "rgba(255, 255, 255, 0.6)",
				borderRadius: "20px",
				borderLeft: "6px solid #22c55e",
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			},
			slideDescription: {
				color: "#166534",
				fontSize: "1.1rem",
				textAlign: "center",
				marginTop: "1rem",
			},
			slideHighlight: {
				background: "linear-gradient(135deg, #22c55e, #16a34a)",
				color: "white",
				padding: "2rem",
				borderRadius: "20px",
				margin: "2rem 0",
				textAlign: "center",
				boxShadow: "0 10px 15px -3px rgba(22, 163, 74, 0.3)",
			},
			slideStats: {
				display: "grid",
				gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
				gap: "2rem",
				margin: "2rem 0",
				width: "100%",
			},
			slideKeypoint: {
				background: "rgba(255, 255, 255, 0.6)",
				padding: "1.5rem",
				borderRadius: "16px",
				textAlign: "center",
				border: "1px solid #bbf7d0",
			},
			slideImage: {
				maxWidth: "100%",
				height: "auto",
				borderRadius: "20px",
				margin: "2rem auto",
				display: "block",
				boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
			},
			twoColumn: {
				display: "flex",
				gap: "3rem",
				width: "100%",
				justifyContent: "space-between",
				alignItems: "flex-start",
			},
			column: {
				flex: 1,
				display: "flex",
				flexDirection: "column",
				gap: "1rem",
			},
		},
	},
];
