export const ROUTES = {
	home: "/",
	signIn: "/sign-in",
	signUp: "/sign-up",
	forgotPassword: "/forgot-password",
	resetPassword: "/reset-password",
	profile: "/profile",
	settings: "/settings",
	generate: "/generate",
	research: "/generate/research",
	marketplace: "/marketplace",
	marketplacePreview: (marketplaceId: string) => `/marketplace/${marketplaceId}/preview`,
	presentations: "/presentations",
	presentationById: (presentationId: number | string) => `/presentations/${presentationId}`,
	presentation: "/presentation",
	presentationError: "/presentation-error",
	purchase: "/purchase",
} as const;
