export const ROUTES = {
	home: "/",
	landing: "/landing",
	signIn: "/sign-in",
	signUp: "/sign-up",
	forgotPassword: "/forgot-password",
	resetPassword: "/reset-password",
	profile: "/profile",
	settings: "/settings",
	generate: "/generate",
	research: "/generate/research",
	outline: "/generate/outline",
	presentations: "/presentations",
	marketplace: "/marketplace",
	templateLibrary: "/marketplace/library",
	templateById: (id: string) => `/marketplace/templates/${encodeURIComponent(id)}`,
	presentationById: (presentationId: string) =>
		`/presentations/${encodeURIComponent(presentationId)}`,
	presentationError: "/presentation-error",
	shared: (token: string) => `/s/${encodeURIComponent(token)}`,
	purchase: "/purchase",
} as const;
